### ISSUE TITLE
Expansion of Caddie to add more players to Wii Sports Resort?

### ISSUE THREAD

**Issue by zarif98** [kiwi515/Caddie#4]
Didn't know the best way to reach you, but I wanted to know if you had any ideas on the decompilation process for Wii Sports Resort table tennis mode? Specifically, in adding more players? I have limited decompilation experience but wanted your insight to see if something like this is even possible at the moment.

**Comment by kiwi515** [comment]
Hello!

Caddie is not a decompilation project, although in theory something like this could be accomplished only by adding new code. I don't know enough about the game engine to pull off something like that, but perhaps someone may do that eventually.

In any case, Caddie is what is known as a "practice mod", so something like this would be outside of its scope. Caddie is simply designed to help time-attack/score-attack players to quickly practice specific situations in-game that would otherwise take much longer to access.

If you'd like to discuss this further, feel free to join [the Discord server](https://discord.gg/BW23QvJaZk)!
